/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Controller.KaryawanController;
import Controller.MemesanController;
import java.awt.Color;
import javax.swing.JOptionPane;
import Model.Karyawan;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JComboBox;

/**
 *
 * @author USER
 */
public class Form_Input extends javax.swing.JFrame {


    /**
     * Creates new form Form_MenuUtama
     */
    KaryawanController controller;
    MemesanController controllerM;
    public Form_Input() {
        initComponents();
        dispose();
        controllerM = new MemesanController(this);
        
        panel_bground2.setBackground(new Color(27,22,22,127));
    }
    
    public javax.swing.JTextField getTxt_idpelanggan(){
        return txt_idpelanggan;
    }
    
    public javax.swing.JTextField getTxt_namapelanggan(){
        return txt_namapelanggan;
    }
    
    public javax.swing.JTextField getTxt_alamat(){
        return txt_alamat;
    }
    
    public javax.swing.JTextField getTxt_nohppelanggan(){
        return txt_nohppelanggan;  
    }
    
    public javax.swing.JTextField getTxt_pesanan(){
        return txt_pesanan;
    }
    
    public javax.swing.JTextField getTxt_biaya(){
        return txt_biaya;
    }
    
    public javax.swing.JTextField getTxt_namagalonman(){
        return txt_namagalonman;
    }
    
    public JComboBox<String> getCbo_idgalonman() {
        return cbo_idgalonman;
    }
    
    public javax.swing.JTextField getTxt_Id(){
        return txt_Id;
    }
    
    public javax.swing.JTextField getTxt_Nama(){
        return txt_Nama;
    }
    
    public javax.swing.JTextField getTxt_Hp(){
        return txt_Hp;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_judul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_menu = new javax.swing.JPanel();
        jLabel_nohp = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();
        jLabel_nama = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_caridata = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_menuutama = new javax.swing.JButton();
        btn_input = new javax.swing.JButton();
        txt_Id = new javax.swing.JTextField();
        txt_Nama = new javax.swing.JTextField();
        txt_Hp = new javax.swing.JTextField();
        jLabel_idpelanggan = new javax.swing.JLabel();
        jLabel_namapelanggan = new javax.swing.JLabel();
        jLabel_alamat = new javax.swing.JLabel();
        jLabel_nohppelanggan = new javax.swing.JLabel();
        jLabel_pesanan = new javax.swing.JLabel();
        jLabel_biaya = new javax.swing.JLabel();
        txt_idpelanggan = new javax.swing.JTextField();
        txt_namapelanggan = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_nohppelanggan = new javax.swing.JTextField();
        txt_pesanan = new javax.swing.JTextField();
        txt_biaya = new javax.swing.JTextField();
        panel_bground2 = new javax.swing.JPanel();
        jLabel_namagalonman = new javax.swing.JLabel();
        txt_namagalonman = new javax.swing.JTextField();
        btn_kirim = new javax.swing.JButton();
        btn_batalkan = new javax.swing.JButton();
        jLabel_idgalonman = new javax.swing.JLabel();
        cbo_idgalonman = new javax.swing.JComboBox<>();
        panel_galon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        panel_judul.setPreferredSize(new java.awt.Dimension(1440, 115));
        panel_judul.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INPUT");
        panel_judul.add(jLabel1);
        jLabel1.setBounds(452, 20, 679, 60);

        jPanel1.add(panel_judul);
        panel_judul.setBounds(0, 0, 1478, 115);

        panel_menu.setBackground(new java.awt.Color(48, 179, 235));
        panel_menu.setLayout(null);

        jLabel_nohp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nohp.setText("NO HP :");
        panel_menu.add(jLabel_nohp);
        jLabel_nohp.setBounds(30, 230, 101, 45);

        jLabel_id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_id.setText("ID :");
        panel_menu.add(jLabel_id);
        jLabel_id.setBounds(30, 130, 101, 45);

        jLabel_nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nama.setText("NAMA :");
        panel_menu.add(jLabel_nama);
        jLabel_nama.setBounds(30, 180, 101, 45);

        btn_logout.setBackground(new java.awt.Color(227, 247, 255));
        btn_logout.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        panel_menu.add(btn_logout);
        btn_logout.setBounds(50, 830, 262, 96);

        btn_caridata.setBackground(new java.awt.Color(227, 247, 255));
        btn_caridata.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_caridata.setText("CARI DATA");
        btn_caridata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caridataActionPerformed(evt);
            }
        });
        panel_menu.add(btn_caridata);
        btn_caridata.setBounds(50, 440, 262, 96);

        btn_laporan.setBackground(new java.awt.Color(227, 247, 255));
        btn_laporan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_laporan.setText("LAPORAN");
        panel_menu.add(btn_laporan);
        btn_laporan.setBounds(50, 700, 262, 96);

        btn_menuutama.setBackground(new java.awt.Color(227, 247, 255));
        btn_menuutama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_menuutama.setText("MENU UTAMA");
        btn_menuutama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuutamaActionPerformed(evt);
            }
        });
        panel_menu.add(btn_menuutama);
        btn_menuutama.setBounds(50, 310, 262, 96);

        btn_input.setBackground(new java.awt.Color(227, 247, 255));
        btn_input.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_input.setText("INPUT");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        panel_menu.add(btn_input);
        btn_input.setBounds(50, 570, 262, 96);

        txt_Id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_menu.add(txt_Id);
        txt_Id.setBounds(160, 130, 180, 45);

        txt_Nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_menu.add(txt_Nama);
        txt_Nama.setBounds(160, 180, 180, 45);

        txt_Hp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_menu.add(txt_Hp);
        txt_Hp.setBounds(160, 230, 180, 45);

        jPanel1.add(panel_menu);
        panel_menu.setBounds(0, 2, 359, 1020);

        jLabel_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_idpelanggan.setText("ID PELANGGAN :");
        jPanel1.add(jLabel_idpelanggan);
        jLabel_idpelanggan.setBounds(396, 163, 228, 47);

        jLabel_namapelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_namapelanggan.setText("NAMA PELANGGAN :");
        jPanel1.add(jLabel_namapelanggan);
        jLabel_namapelanggan.setBounds(396, 241, 228, 47);

        jLabel_alamat.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_alamat.setText("ALAMAT :");
        jPanel1.add(jLabel_alamat);
        jLabel_alamat.setBounds(396, 319, 228, 47);

        jLabel_nohppelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nohppelanggan.setText("NO HP :");
        jPanel1.add(jLabel_nohppelanggan);
        jLabel_nohppelanggan.setBounds(396, 397, 228, 47);

        jLabel_pesanan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_pesanan.setText("PESANAN :");
        jPanel1.add(jLabel_pesanan);
        jLabel_pesanan.setBounds(396, 475, 228, 47);

        jLabel_biaya.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_biaya.setText("BIAYA :");
        jPanel1.add(jLabel_biaya);
        jLabel_biaya.setBounds(396, 553, 228, 47);

        txt_idpelanggan.setBackground(new java.awt.Color(196, 196, 196));
        txt_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_idpelanggan);
        txt_idpelanggan.setBounds(679, 167, 377, 40);

        txt_namapelanggan.setBackground(new java.awt.Color(196, 196, 196));
        txt_namapelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_namapelanggan);
        txt_namapelanggan.setBounds(679, 245, 377, 40);

        txt_alamat.setBackground(new java.awt.Color(196, 196, 196));
        txt_alamat.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_alamat);
        txt_alamat.setBounds(679, 323, 377, 40);

        txt_nohppelanggan.setBackground(new java.awt.Color(196, 196, 196));
        txt_nohppelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_nohppelanggan);
        txt_nohppelanggan.setBounds(679, 401, 377, 40);

        txt_pesanan.setBackground(new java.awt.Color(196, 196, 196));
        txt_pesanan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txt_pesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pesananKeyTyped(evt);
            }
        });
        jPanel1.add(txt_pesanan);
        txt_pesanan.setBounds(679, 479, 377, 40);

        txt_biaya.setBackground(new java.awt.Color(196, 196, 196));
        txt_biaya.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_biaya);
        txt_biaya.setBounds(679, 557, 377, 40);

        panel_bground2.setBackground(new java.awt.Color(255, 255, 255));
        panel_bground2.setLayout(null);

        jLabel_namagalonman.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_namagalonman.setText("NAMA GALONMAN :");
        panel_bground2.add(jLabel_namagalonman);
        jLabel_namagalonman.setBounds(40, 570, 228, 47);

        txt_namagalonman.setBackground(new java.awt.Color(196, 196, 196));
        txt_namagalonman.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_bground2.add(txt_namagalonman);
        txt_namagalonman.setBounds(320, 570, 377, 40);

        btn_kirim.setBackground(new java.awt.Color(0, 255, 25));
        btn_kirim.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_kirim.setText("KIRIM");
        btn_kirim.setBorder(null);
        btn_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimActionPerformed(evt);
            }
        });
        panel_bground2.add(btn_kirim);
        btn_kirim.setBounds(390, 750, 262, 96);

        btn_batalkan.setBackground(new java.awt.Color(255, 0, 0));
        btn_batalkan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_batalkan.setText("BATALKAN");
        btn_batalkan.setBorder(null);
        btn_batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalkanActionPerformed(evt);
            }
        });
        panel_bground2.add(btn_batalkan);
        btn_batalkan.setBounds(750, 750, 262, 96);

        jLabel_idgalonman.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_idgalonman.setText("ID GALONMAN :");
        panel_bground2.add(jLabel_idgalonman);
        jLabel_idgalonman.setBounds(40, 510, 228, 47);

        cbo_idgalonman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel_bground2.add(cbo_idgalonman);
        cbo_idgalonman.setBounds(320, 510, 377, 40);

        jPanel1.add(panel_bground2);
        panel_bground2.setBounds(358, 113, 1082, 911);

        panel_galon.setMinimumSize(new java.awt.Dimension(893, 861));
        panel_galon.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GALON.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(893, 163));
        jLabel2.setRequestFocusEnabled(false);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        panel_galon.add(jLabel2);
        jLabel2.setBounds(0, 0, 893, 861);

        jPanel1.add(panel_galon);
        panel_galon.setBounds(431, 163, 893, 861);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        
        int response = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar ?", "LOGOUT", JOptionPane.YES_NO_OPTION);
            
        if(response == JOptionPane.YES_OPTION){
                    new Form_Login().show();
        }                                          
        else if(response==JOptionPane.NO_OPTION){
            
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_batalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalkanActionPerformed
        // TODO add your handling code here:
        
        int response = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus ?", "DELETE", JOptionPane.YES_NO_OPTION);
            
        if(response == JOptionPane.YES_OPTION){
            // Isi fungsinya disini ...        
        }                                          
        else if(response==JOptionPane.NO_OPTION){
            // Isi fungsinya disini ...
        }
        
    }//GEN-LAST:event_btn_batalkanActionPerformed

    private void btn_caridataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caridataActionPerformed
        // TODO add your handling code here:
        Form_Caridata f = new Form_Caridata();
            f.setVisible(true);
            f.toFront();
            f.getTxt_Id().setText(getTxt_Id().getText());
            f.getTxt_Id().setEditable(false);
            f.getTxt_Nama().setText(getTxt_Nama().getText());
            f.getTxt_Nama().setEditable(false);
            f.getTxt_Hp().setText(getTxt_Hp().getText());
            f.getTxt_Hp().setEditable(false);
    }//GEN-LAST:event_btn_caridataActionPerformed

    private void btn_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimActionPerformed
        // TODO add your handling code here:
        controllerM.Kirim();
        
    }//GEN-LAST:event_btn_kirimActionPerformed

    private void txt_pesananKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesananKeyTyped
        // TODO add your handling code here:
        try{
            int x = Integer.parseInt(getTxt_pesanan().getText());
            int biaya = x*5000;
            getTxt_biaya().setText(biaya + "");
        }
        catch(NumberFormatException e){}
                
    }//GEN-LAST:event_txt_pesananKeyTyped

    private void btn_menuutamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuutamaActionPerformed
        // TODO add your handling code here:
        Form_MenuUtama f = new Form_MenuUtama();
            f.setVisible(true);
            f.toFront();
            f.getTxt_Id().setText(getTxt_Id().getText());
            f.getTxt_Id().setEditable(false);
            f.getTxt_Nama().setText(getTxt_Nama().getText());
            f.getTxt_Nama().setEditable(false);
            f.getTxt_Hp().setText(getTxt_Hp().getText());
            f.getTxt_Hp().setEditable(false);
    }//GEN-LAST:event_btn_menuutamaActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        Form_Input f = new Form_Input();
            f.setVisible(true);
            f.toFront();
            f.getTxt_Id().setText(getTxt_Id().getText());
            f.getTxt_Id().setEditable(false);
            f.getTxt_Nama().setText(getTxt_Nama().getText());
            f.getTxt_Nama().setEditable(false);
            f.getTxt_Hp().setText(getTxt_Hp().getText());
            f.getTxt_Hp().setEditable(false);
    }//GEN-LAST:event_btn_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batalkan;
    private javax.swing.JButton btn_caridata;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_kirim;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_menuutama;
    private javax.swing.JComboBox<String> cbo_idgalonman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_alamat;
    private javax.swing.JLabel jLabel_biaya;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_idgalonman;
    private javax.swing.JLabel jLabel_idpelanggan;
    private javax.swing.JLabel jLabel_nama;
    private javax.swing.JLabel jLabel_namagalonman;
    private javax.swing.JLabel jLabel_namapelanggan;
    private javax.swing.JLabel jLabel_nohp;
    private javax.swing.JLabel jLabel_nohppelanggan;
    private javax.swing.JLabel jLabel_pesanan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_bground2;
    private javax.swing.JPanel panel_galon;
    private javax.swing.JPanel panel_judul;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JTextField txt_Hp;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Nama;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_biaya;
    private javax.swing.JTextField txt_idpelanggan;
    private javax.swing.JTextField txt_namagalonman;
    private javax.swing.JTextField txt_namapelanggan;
    private javax.swing.JTextField txt_nohppelanggan;
    private javax.swing.JTextField txt_pesanan;
    // End of variables declaration//GEN-END:variables
}
