/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Color;
import javax.swing.border.Border;
import javax.swing.table.TableColumn;

/**
 *
 * @author USER
 */
public class Form_Laporan extends javax.swing.JFrame {


    /**
     * Creates new form Form_MenuUtama
     */
    public Form_Laporan() {
        initComponents();
        //panel_galon.setBackground(new Color(225,225,225,255));
        paneljudul_table.setBackground(new Color(229,229,229,242));
        table.setBackground(new Color(255,255,255,0));
        table.setDefaultRenderer(Object.class, new table_warna(new Color(255,255,255,178), new Color(243,243,243,229)));
        //table.setBorder((Border) new Color(0,0,0,0));
        lebarKolom();
        table.setRowHeight(50);
        
    }
    
    public void lebarKolom(){ 
        TableColumn column;
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = table.getColumnModel().getColumn(0); 
        column.setPreferredWidth(140);
        column = table.getColumnModel().getColumn(1); 
        column.setPreferredWidth(140); 
        column = table.getColumnModel().getColumn(2); 
        column.setPreferredWidth(140); 
        column = table.getColumnModel().getColumn(3); 
        column.setPreferredWidth(140); 
        column = table.getColumnModel().getColumn(4); 
        column.setPreferredWidth(140);
        column = table.getColumnModel().getColumn(5); 
        column.setPreferredWidth(140); 
        column = table.getColumnModel().getColumn(6); 
        column.setPreferredWidth(140); 
        column = table.getColumnModel().getColumn(7); 
        column.setPreferredWidth(140); 
        column = table.getColumnModel().getColumn(8); 
        column.setPreferredWidth(140); 
        
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_judul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JTextField();
        txt_cari = new javax.swing.JTextField();
        btn_batalkan = new javax.swing.JButton();
        btn_cetak = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        btn_tanggal = new javax.swing.JButton();
        table = new javax.swing.JTable();
        judultable_idpelanggan = new javax.swing.JLabel();
        judultable_idkaryawan = new javax.swing.JLabel();
        judultable_idk_antar = new javax.swing.JLabel();
        judultable_nama = new javax.swing.JLabel();
        judultable_jml = new javax.swing.JLabel();
        judultable_diskon = new javax.swing.JLabel();
        judultable_voucher = new javax.swing.JLabel();
        judultable_tglpesanan = new javax.swing.JLabel();
        judultable_jmlpembayaran = new javax.swing.JLabel();
        paneljudul_table = new javax.swing.JPanel();
        panel_galon = new javax.swing.JPanel();
        gambar_galon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1478, 1024));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        panel_judul.setPreferredSize(new java.awt.Dimension(1440, 115));
        panel_judul.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAPORAN");
        panel_judul.add(jLabel1);
        jLabel1.setBounds(452, 20, 679, 60);

        jPanel1.add(panel_judul);
        panel_judul.setBounds(0, 0, 1478, 115);

        txt_tanggal.setBackground(new java.awt.Color(196, 196, 196));
        txt_tanggal.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_tanggal);
        txt_tanggal.setBounds(770, 144, 290, 45);

        txt_cari.setBackground(new java.awt.Color(196, 196, 196));
        txt_cari.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_cari);
        txt_cari.setBounds(172, 144, 290, 45);

        btn_batalkan.setBackground(new java.awt.Color(48, 179, 235));
        btn_batalkan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_batalkan.setText("BATALKAN");
        btn_batalkan.setBorder(null);
        btn_batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalkanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batalkan);
        btn_batalkan.setBounds(95, 690, 332, 96);

        btn_cetak.setBackground(new java.awt.Color(48, 179, 235));
        btn_cetak.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_cetak.setText("CETAK LAPORAN");
        btn_cetak.setBorder(null);
        jPanel1.add(btn_cetak);
        btn_cetak.setBounds(1012, 690, 332, 96);

        btn_cari.setBackground(new java.awt.Color(196, 196, 196));
        btn_cari.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_cari.setText("CARI");
        jPanel1.add(btn_cari);
        btn_cari.setBounds(473, 144, 143, 45);

        btn_tanggal.setBackground(new java.awt.Color(196, 196, 196));
        btn_tanggal.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_tanggal.setText("CARI");
        jPanel1.add(btn_tanggal);
        btn_tanggal.setBounds(1071, 144, 143, 45);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "ID Karyawan", "ID K.Antar", "Nama Pelanggan", "Jumlah Pesanan", "Diskon", "Voucher", "Tanggal Pesanan", "Jumlah Pembayaran"
            }
        ));
        table.setGridColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(table);
        table.setBounds(95, 274, 1250, 344);

        judultable_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_idpelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_idpelanggan.setText("ID Pelanggan");
        judultable_idpelanggan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_idpelanggan);
        judultable_idpelanggan.setBounds(95, 225, 140, 50);

        judultable_idkaryawan.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_idkaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_idkaryawan.setText("ID Karyawan");
        judultable_idkaryawan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_idkaryawan);
        judultable_idkaryawan.setBounds(234, 225, 140, 50);

        judultable_idk_antar.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_idk_antar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_idk_antar.setText("ID K.Antar");
        judultable_idk_antar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_idk_antar);
        judultable_idk_antar.setBounds(374, 225, 140, 50);

        judultable_nama.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_nama.setText("Nama Pelanggan");
        judultable_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_nama);
        judultable_nama.setBounds(512, 225, 140, 50);

        judultable_jml.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_jml.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_jml.setText("Jumlah Pesanan");
        judultable_jml.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_jml);
        judultable_jml.setBounds(650, 225, 140, 50);

        judultable_diskon.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_diskon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_diskon.setText("Diskon");
        judultable_diskon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_diskon);
        judultable_diskon.setBounds(790, 225, 140, 50);

        judultable_voucher.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_voucher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_voucher.setText("Voucher");
        judultable_voucher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_voucher);
        judultable_voucher.setBounds(929, 225, 140, 50);

        judultable_tglpesanan.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_tglpesanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_tglpesanan.setText("Tanggal Pesanan");
        judultable_tglpesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_tglpesanan);
        judultable_tglpesanan.setBounds(1067, 225, 140, 50);

        judultable_jmlpembayaran.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_jmlpembayaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_jmlpembayaran.setText("Jumlah Pembayaran");
        judultable_jmlpembayaran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        judultable_jmlpembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        judultable_jmlpembayaran.setFocusable(false);
        jPanel1.add(judultable_jmlpembayaran);
        judultable_jmlpembayaran.setBounds(1205, 225, 140, 50);

        paneljudul_table.setBackground(new java.awt.Color(229, 229, 229));
        paneljudul_table.setLayout(null);
        jPanel1.add(paneljudul_table);
        paneljudul_table.setBounds(95, 225, 1251, 50);

        panel_galon.setMinimumSize(new java.awt.Dimension(893, 861));
        panel_galon.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panel_galonAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        panel_galon.setLayout(null);

        gambar_galon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GALON.jpg"))); // NOI18N
        gambar_galon.setPreferredSize(new java.awt.Dimension(893, 163));
        gambar_galon.setRequestFocusEnabled(false);
        gambar_galon.setVerifyInputWhenFocusTarget(false);
        panel_galon.add(gambar_galon);
        gambar_galon.setBounds(0, 0, 893, 861);

        jPanel1.add(panel_galon);
        panel_galon.setBounds(274, 114, 893, 861);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_galonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panel_galonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_galonAncestorAdded

    private void btn_batalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batalkan;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_tanggal;
    private javax.swing.JLabel gambar_galon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judultable_diskon;
    private javax.swing.JLabel judultable_idk_antar;
    private javax.swing.JLabel judultable_idkaryawan;
    private javax.swing.JLabel judultable_idpelanggan;
    private javax.swing.JLabel judultable_jml;
    private javax.swing.JLabel judultable_jmlpembayaran;
    private javax.swing.JLabel judultable_nama;
    private javax.swing.JLabel judultable_tglpesanan;
    private javax.swing.JLabel judultable_voucher;
    private javax.swing.JPanel panel_galon;
    private javax.swing.JPanel panel_judul;
    private javax.swing.JPanel paneljudul_table;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_tanggal;
    // End of variables declaration//GEN-END:variables
}
