/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.border.Border;
import javax.swing.table.TableColumn;

/**
 *
 * @author USER
 */
public class Form_CRUD extends javax.swing.JFrame {


    /**
     * Creates new form Form_MenuUtama
     */
    public Form_CRUD() {
        initComponents();
        //panel_galon.setBackground(new Color(225,225,225,255));
        paneljudul_table.setBackground(new Color(229,229,229,242));
        table_edit.setBackground(new Color(255,255,255,0));
        table_edit.setDefaultRenderer(Object.class, new table_warna(new Color(255,255,255,178), new Color(243,243,243,229)));
        //table.setBorder((Border) new Color(0,0,0,0));
        lebarKolom();
        table_edit.setRowHeight(50);
        
    }
    
    public void lebarKolom(){ 
        TableColumn column;
        table_edit.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = table_edit.getColumnModel().getColumn(0); 
        column.setPreferredWidth(140);
        column = table_edit.getColumnModel().getColumn(1); 
        column.setPreferredWidth(140); 
        column = table_edit.getColumnModel().getColumn(2); 
        column.setPreferredWidth(140); 
        column = table_edit.getColumnModel().getColumn(3); 
        column.setPreferredWidth(140); 
        column = table_edit.getColumnModel().getColumn(4); 
        column.setPreferredWidth(140);
        column = table_edit.getColumnModel().getColumn(5); 
        column.setPreferredWidth(140); 
        column = table_edit.getColumnModel().getColumn(6); 
        column.setPreferredWidth(140); 
        column = table_edit.getColumnModel().getColumn(7); 
        column.setPreferredWidth(140); 
        column = table_edit.getColumnModel().getColumn(8); 
        column.setPreferredWidth(140); 
        
    }
    
    public javax.swing.JTextField getTxt_idpelanggan(){
        return txt_idpelanggan;
    }
    
    public javax.swing.JTextField getTxt_namapelanggan(){
        return txt_namapelanggan;
    }
    
    public javax.swing.JTextField getTxt_alamat(){
        return txt_alamat;
    }
    
    public javax.swing.JTextField getTxt_nohppelanggan(){
        return txt_nohppelanggan;  
    }
    
    public javax.swing.JTextField getTxt_pesanan(){
        return txt_pesanan;
    }
    
    public javax.swing.JTextField getTxt_biaya(){
        return txt_biaya;
    }
    
    public javax.swing.JTextField getTxt_namagalonman(){
        return txt_namagalonman;
    }
    
    public JComboBox<String> getCbo_idgalonman() {
        return cbo_idgalonman;
    }
    
    public javax.swing.JTable getTable_Edit(){
        return table_edit;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_judul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_batalkan = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        table_edit = new javax.swing.JTable();
        judultable_idpelanggan = new javax.swing.JLabel();
        judultable_idkaryawan = new javax.swing.JLabel();
        judultable_idgalonman = new javax.swing.JLabel();
        judultable_nama = new javax.swing.JLabel();
        judultable_jml = new javax.swing.JLabel();
        judultable_diskon = new javax.swing.JLabel();
        judultable_voucher = new javax.swing.JLabel();
        judultable_tglpesanan = new javax.swing.JLabel();
        judultable_jmlpembayaran = new javax.swing.JLabel();
        jLabel_idpelanggan = new javax.swing.JLabel();
        txt_idpelanggan = new javax.swing.JTextField();
        jLabel_namapelanggan = new javax.swing.JLabel();
        txt_namapelanggan = new javax.swing.JTextField();
        jLabel_alamat = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        jLabel_nohppelanggan = new javax.swing.JLabel();
        txt_nohppelanggan = new javax.swing.JTextField();
        txt_pesanan = new javax.swing.JTextField();
        txt_biaya = new javax.swing.JTextField();
        cbo_idgalonman = new javax.swing.JComboBox<>();
        jLabel_namagalonman = new javax.swing.JLabel();
        txt_namagalonman = new javax.swing.JTextField();
        jLabel_pesanan = new javax.swing.JLabel();
        jLabel_biaya = new javax.swing.JLabel();
        jLabel_idgalonman = new javax.swing.JLabel();
        paneljudul_table = new javax.swing.JPanel();
        panel_galon = new javax.swing.JPanel();
        gambar_galon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1478, 1024));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        panel_judul.setPreferredSize(new java.awt.Dimension(1440, 115));
        panel_judul.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDIT");
        panel_judul.add(jLabel1);
        jLabel1.setBounds(452, 20, 679, 60);

        jPanel1.add(panel_judul);
        panel_judul.setBounds(0, 0, 1478, 115);

        btn_batalkan.setBackground(new java.awt.Color(48, 179, 235));
        btn_batalkan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_batalkan.setText("BATALKAN");
        btn_batalkan.setBorder(null);
        btn_batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalkanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batalkan);
        btn_batalkan.setBounds(95, 874, 332, 96);

        btn_update.setBackground(new java.awt.Color(48, 179, 235));
        btn_update.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.setBorder(null);
        jPanel1.add(btn_update);
        btn_update.setBounds(1010, 874, 332, 96);

        btn_delete.setBackground(new java.awt.Color(48, 179, 235));
        btn_delete.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.setBorder(null);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete);
        btn_delete.setBounds(550, 874, 332, 96);

        table_edit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "ID Karyawan", "ID Galonman", "Nama Pelanggan", "Jumlah Pesanan", "Diskon", "Voucher", "Tanggal Pesanan", "Jumlah Pembayaran"
            }
        ));
        table_edit.setGridColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(table_edit);
        table_edit.setBounds(95, 220, 1250, 160);

        judultable_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_idpelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_idpelanggan.setText("ID Pelanggan");
        judultable_idpelanggan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_idpelanggan);
        judultable_idpelanggan.setBounds(95, 150, 140, 50);

        judultable_idkaryawan.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_idkaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_idkaryawan.setText("ID Karyawan");
        judultable_idkaryawan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_idkaryawan);
        judultable_idkaryawan.setBounds(234, 150, 140, 50);

        judultable_idgalonman.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_idgalonman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_idgalonman.setText("ID Galonman");
        judultable_idgalonman.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_idgalonman);
        judultable_idgalonman.setBounds(374, 150, 140, 50);

        judultable_nama.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_nama.setText("Nama Pelanggan");
        judultable_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_nama);
        judultable_nama.setBounds(512, 150, 140, 50);

        judultable_jml.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_jml.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_jml.setText("Jumlah Pesanan");
        judultable_jml.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_jml);
        judultable_jml.setBounds(650, 150, 140, 50);

        judultable_diskon.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_diskon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_diskon.setText("Diskon");
        judultable_diskon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_diskon);
        judultable_diskon.setBounds(790, 150, 140, 50);

        judultable_voucher.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_voucher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_voucher.setText("Voucher");
        judultable_voucher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_voucher);
        judultable_voucher.setBounds(929, 150, 140, 50);

        judultable_tglpesanan.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_tglpesanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_tglpesanan.setText("Tanggal Pesanan");
        judultable_tglpesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(judultable_tglpesanan);
        judultable_tglpesanan.setBounds(1067, 150, 140, 50);

        judultable_jmlpembayaran.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        judultable_jmlpembayaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_jmlpembayaran.setText("Jumlah Pembayaran");
        judultable_jmlpembayaran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        judultable_jmlpembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        judultable_jmlpembayaran.setFocusable(false);
        jPanel1.add(judultable_jmlpembayaran);
        judultable_jmlpembayaran.setBounds(1205, 150, 140, 50);

        jLabel_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_idpelanggan.setText("ID PELANGGAN :");
        jPanel1.add(jLabel_idpelanggan);
        jLabel_idpelanggan.setBounds(30, 540, 228, 47);

        txt_idpelanggan.setBackground(new java.awt.Color(196, 196, 196));
        txt_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_idpelanggan);
        txt_idpelanggan.setBounds(310, 540, 377, 40);

        jLabel_namapelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_namapelanggan.setText("NAMA PELANGGAN :");
        jPanel1.add(jLabel_namapelanggan);
        jLabel_namapelanggan.setBounds(30, 610, 228, 47);

        txt_namapelanggan.setBackground(new java.awt.Color(196, 196, 196));
        txt_namapelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_namapelanggan);
        txt_namapelanggan.setBounds(310, 620, 377, 40);

        jLabel_alamat.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_alamat.setText("ALAMAT :");
        jPanel1.add(jLabel_alamat);
        jLabel_alamat.setBounds(30, 690, 228, 47);

        txt_alamat.setBackground(new java.awt.Color(196, 196, 196));
        txt_alamat.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_alamat);
        txt_alamat.setBounds(310, 700, 377, 40);

        jLabel_nohppelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nohppelanggan.setText("NO HP :");
        jPanel1.add(jLabel_nohppelanggan);
        jLabel_nohppelanggan.setBounds(30, 770, 228, 47);

        txt_nohppelanggan.setBackground(new java.awt.Color(196, 196, 196));
        txt_nohppelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_nohppelanggan);
        txt_nohppelanggan.setBounds(310, 770, 377, 40);

        txt_pesanan.setBackground(new java.awt.Color(196, 196, 196));
        txt_pesanan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txt_pesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pesananKeyTyped(evt);
            }
        });
        jPanel1.add(txt_pesanan);
        txt_pesanan.setBounds(1030, 540, 377, 40);

        txt_biaya.setBackground(new java.awt.Color(196, 196, 196));
        txt_biaya.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_biaya);
        txt_biaya.setBounds(1030, 620, 377, 40);

        cbo_idgalonman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_idgalonman);
        cbo_idgalonman.setBounds(1030, 700, 377, 40);

        jLabel_namagalonman.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_namagalonman.setText("NAMA GALONMAN :");
        jPanel1.add(jLabel_namagalonman);
        jLabel_namagalonman.setBounds(750, 770, 228, 47);

        txt_namagalonman.setBackground(new java.awt.Color(196, 196, 196));
        txt_namagalonman.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_namagalonman);
        txt_namagalonman.setBounds(1030, 780, 377, 40);

        jLabel_pesanan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_pesanan.setText("PESANAN :");
        jPanel1.add(jLabel_pesanan);
        jLabel_pesanan.setBounds(750, 540, 228, 47);

        jLabel_biaya.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_biaya.setText("BIAYA :");
        jPanel1.add(jLabel_biaya);
        jLabel_biaya.setBounds(750, 620, 228, 47);

        jLabel_idgalonman.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_idgalonman.setText("ID GALONMAN :");
        jPanel1.add(jLabel_idgalonman);
        jLabel_idgalonman.setBounds(750, 690, 228, 47);

        paneljudul_table.setBackground(new java.awt.Color(229, 229, 229));
        paneljudul_table.setLayout(null);
        jPanel1.add(paneljudul_table);
        paneljudul_table.setBounds(95, 150, 1251, 50);

        panel_galon.setMinimumSize(new java.awt.Dimension(893, 861));
        panel_galon.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panel_galonAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        panel_galon.setLayout(null);

        gambar_galon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GALON.jpg"))); // NOI18N
        gambar_galon.setPreferredSize(new java.awt.Dimension(893, 163));
        gambar_galon.setRequestFocusEnabled(false);
        gambar_galon.setVerifyInputWhenFocusTarget(false);
        panel_galon.add(gambar_galon);
        gambar_galon.setBounds(0, 0, 893, 861);

        jPanel1.add(panel_galon);
        panel_galon.setBounds(274, 114, 893, 861);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_galonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panel_galonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_galonAncestorAdded

    private void btn_batalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalkanActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void txt_pesananKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pesananKeyTyped
        // TODO add your handling code here:
        try{
            int x = Integer.parseInt(getTxt_pesanan().getText());
            int biaya = x*5000;
            getTxt_biaya().setText(biaya + "");
        }
        catch(NumberFormatException e){}

    }//GEN-LAST:event_txt_pesananKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batalkan;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cbo_idgalonman;
    private javax.swing.JLabel gambar_galon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_alamat;
    private javax.swing.JLabel jLabel_biaya;
    private javax.swing.JLabel jLabel_idgalonman;
    private javax.swing.JLabel jLabel_idpelanggan;
    private javax.swing.JLabel jLabel_namagalonman;
    private javax.swing.JLabel jLabel_namapelanggan;
    private javax.swing.JLabel jLabel_nohppelanggan;
    private javax.swing.JLabel jLabel_pesanan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judultable_diskon;
    private javax.swing.JLabel judultable_idgalonman;
    private javax.swing.JLabel judultable_idkaryawan;
    private javax.swing.JLabel judultable_idpelanggan;
    private javax.swing.JLabel judultable_jml;
    private javax.swing.JLabel judultable_jmlpembayaran;
    private javax.swing.JLabel judultable_nama;
    private javax.swing.JLabel judultable_tglpesanan;
    private javax.swing.JLabel judultable_voucher;
    private javax.swing.JPanel panel_galon;
    private javax.swing.JPanel panel_judul;
    private javax.swing.JPanel paneljudul_table;
    private javax.swing.JTable table_edit;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_biaya;
    private javax.swing.JTextField txt_idpelanggan;
    private javax.swing.JTextField txt_namagalonman;
    private javax.swing.JTextField txt_namapelanggan;
    private javax.swing.JTextField txt_nohppelanggan;
    private javax.swing.JTextField txt_pesanan;
    // End of variables declaration//GEN-END:variables
}
